BaseUrl= "https://www.friedenslager-petersdorf.eu/"
LanguageCode= "de-DE"
Title= "Friedenslager Petersdorf e.V."
paginate = 5
DisqusShortname = "Petersdorf"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme = "casper"

[params]
  description = "Verein für interkulturelle Zusammenarbeit zur Regionalentwicklung in Westrumänien."
  cover = ""
  author = "Friedenslager Petersdorf"
  logo = "images/logo-top-left.png"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "Startseite"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Verein"
  weight = -119
  identifier = "verein"
  url = "/tags/verein"

[[menu.main]]
  name = "Kontakt"
  weight = 100
  identifier = "kontakt"
  url = "/kontakt"

[[menu.main]]
  name = "Aktuelles"
  weigth = -118
  identifier = "aktuelles"
  url = "/tags/aktuelles"
